name: all-signs-options-shopify
services:
  pgdb:
    container_name: pgdb
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB} 
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - aso-network
    ports:
      - 5432:5432

  frontend-app:
    image: vertimcoders/all-signs-options:latest
    restart: unless-stopped
    environment:
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
      SHOPIFY_API_SECRET: ${SHOPIFY_API_SECRET}
      SCOPES: ${SCOPES}
      SHOPIFY_ALL_SIGNS_OPTIONS_FRONTEND_ID: ${SHOPIFY_ALL_SIGNS_OPTIONS_FRONTEND_ID}
      SHOPIFY_ASO_ADMIN_ORDER_DETAIL_ID: ${SHOPIFY_ASO_ADMIN_ORDER_DETAIL_ID}
      DATABASE_URL: ${DATABASE_URL}
      SHOP_CUSTOM_DOMAIN: ${SHOP_CUSTOM_DOMAIN}
      SHOPIFY_APP_URL: ${SHOPIFY_APP_URL}
      IS_TEST: ${IS_TEST}
      APP_URL: ${APP_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - pgdb 
    networks:
      - aso-network
      - proxy-network

networks:
  aso-network:
  proxy-network:
    name: proxy-network
    external: true
