# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62c19e186a7ae5690b3c3bbcdad0fae6"
name = "all-signs-customizer"
application_url = "https://all-sign-options-shopify-test.onrender.com"
embedded = true
handle = "all-signs-customizer"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ncpc-dev.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_product_listings,read_products,read_publications,read_themes,write_products,write_publications"

[auth]
redirect_urls = [
  "https://all-sign-options-shopify-test.onrender.com/auth/callback",
  "https://all-sign-options-shopify-test.onrender.com/auth/shopify/callback",
  "https://all-sign-options-shopify-test.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://all-sign-options-shopify-test.onrender.com"
subpath = "aso-proxy"
prefix = "apps"

[pos]
embedded = false
