# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62c19e186a7ae5690b3c3bbcdad0fae6"
name = "all-signs-options-two"
application_url = "https://mud-industries-h-vienna.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "local-aso-dev-two.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_product_listings,read_products,read_publications,read_themes,write_products,write_publications"

[auth]
redirect_urls = [
  "https://mud-industries-h-vienna.trycloudflare.com/auth/callback",
  "https://mud-industries-h-vienna.trycloudflare.com/auth/shopify/callback",
  "https://mud-industries-h-vienna.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://mud-industries-h-vienna.trycloudflare.com"
subpath = "aso-proxy"
prefix = "apps"

[pos]
embedded = false
