# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adf4506adb0b3a2e093f1a910b28e181"
name = "All Signs Option"
application_url = "https://different-til-quiz-sciences.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5c91f330.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://different-til-quiz-sciences.trycloudflare.com/auth/callback",
  "https://different-til-quiz-sciences.trycloudflare.com/auth/shopify/callback",
  "https://different-til-quiz-sciences.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
