# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adf4506adb0b3a2e093f1a910b28e181"
name = "All Signs Options"
application_url = "https://aso-app.vertimcoders.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-5c91f330.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_product_listings,read_products,read_publications,read_themes,write_products,write_publications"

[auth]
redirect_urls = [
  "https://aso-app.vertimcoders.com//auth/callback",
  "https://aso-app.vertimcoders.com//auth/shopify/callback",
  "https://aso-app.vertimcoders.com//api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  # Webhooks de conformité obligatoires pour l'App Store
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"

[app_proxy]
url = "https://aso-app.vertimcoders.com/"
subpath = "aso-proxy"
prefix = "apps"

[pos]
embedded = false
