# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a61b030b2857ab64af1ab238b1e46ed4"
name = "all-signs-option"
handle = "all-signs-option-3"
application_url = "https://acrylic-ports-scoop-lit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_product_listings,read_products,read_publications,read_themes,write_products,write_publications"

[auth]
redirect_urls = [
  "https://acrylic-ports-scoop-lit.trycloudflare.com/auth/callback",
  "https://acrylic-ports-scoop-lit.trycloudflare.com/auth/shopify/callback",
  "https://acrylic-ports-scoop-lit.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
