import { ConfigurationType } from "~/types/ConfigurationType";

export const configurationDemoData: ConfigurationType[] = [
  {
    id: 63,
    name: "Aso  configuration Test",
    description: "Aso  configuration Test",
    icon: "/uploads/clipart111.png",
    popupImg: "<p>Aso &nbsp;configuration Test</p>",
    data: {
      settings: {
        generals: {
          mobile: {
            showNavigatorMenu: "off",
            showNavigationMenuFirst: "yes",
            mobileSelectionOptionsDisplay: "horizontally",
          },
          output: {
            waterMark: "",
            filesFormat: "png",
            zipOutputFiles: {
              active: false,
              zipOutFolderPrefix: "aso_",
            },
            designComposition: false,
          },
          product: {
            designFromScratch: true,
            redirectAfterAddingToCart: true,
            hideDesignButtonsOnShopPage: true,
            hideAddToCartButtonOnShopPage: false,
            hideAddToCartButtonOnDetailPage: false,
          },
        },
        themeColors: {
          skin: "default",
          colors: {
            textColorButton: "#000000",
            backgroundButton: "#000000",
            textColorButtonHelp: "#000000",
            textColorButtonSave: "#000000",
            textColorHoverButton: "#000000",
            textColorOptionsMenu: "#000000",
            backgroundColorHeader: "#000000",
            textColorContentHeader: "#000000",
            textColorContentSideMenu: "#000000",
            textColorHoverButtonHelp: "#000000",
            textColorHoverButtonSave: "#000000",
            backgroundColorButtonHelp: "#000000",
            textColorButtonRestartAll: "#000000",
            backgroundColorHoverButton: "#000000",
            backgroundColorOptionsMenu: "#000000",
            backgroundColorTextButtonSave: "#000000",
            backgroundColorHoverButtonHelp: "#000000",
            backgroundColorHoverButtonSave: "#000000",
            textColorHoverButtonRestartAll: "#000000",
            backgroundColorButtonRestartAll: "#000000",
            backgroundColorHeaderContentSide: "#000000",
            backgroundColorHoverButtonRestartAll: "#000000",
          },
        },
        customizerSign: {
          text: {
            colors: [],
            enableBold: true,
            enableBorder: true,
            enableItalic: true,
            enableStrike: true,
            enableOpacity: true,
            selectedFonts: [],
            enableCurvedUp: false,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 30,
              minimumFontSize: 12,
            },
            enableOverline: true,
            enableUnderline: true,
            enableCurvedDown: false,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          images: {
            filter: {
              active: true,
              enableBlur: true,
              enableSepia: true,
              enableEmbross: true,
              enableOpacity: true,
              enableSharpen: true,
              enableGreyscale: false,
            },
            enableClipart: {
              active: true,
              selectClipartGroups: [2],
            },
            fileUploadScript: {
              uploadMaxWidth: 100,
              uploadMinWidth: 100,
              customWithGraphical: false,
              allowedUploadsExtentions: ["png"],
            },
            enableUploadImage: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: false,
              enableCopyDesignFromSide: true,
            },
          },
          customizerOptions: {
            measurementUnit: "cm",
            desktopColumnOrder: "right",
            showDayNightButton: "display",
            showHideMeasurements: "both",
            decimalFormatMeasurements: "with-decimal",
          },
        },
        languageImages: {
          images: {
            icon: "",
            resetAllIcon: "",
            cancelAnAction: "",
            changeIconSize: "",
            changeIconText: "",
            changeIconColor: "",
            changeIconImage: "",
            changeIconShape: "",
            changeIconShare: "",
            changeIconBorder: "",
            changeIconImport: "",
            changeIconPreview: "",
            changeIconProduct: "",
            changeIconMaterial: "",
            changeIconSizeMenu: "",
            changeIconSaveProject: "",
            changeIconFixingMethod: "",
            changeIconShareSideBar: "",
          },
          visualizer: {
            textHelp: "Help",
            textSave: "Save",
            textSize: "Size",
            textColor: "Color",
            textImage: "Image",
            textShape: "Shape",
            textShare: "Share",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Plastic Signs",
            textDownload: "Download",
            textMaterial: "Material",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textOptionText: "Text",
            textButtonFinish: "Finish",
            textButtonRefresh: "Restart all",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
          },
          uploadDesign: {
            link: "",
            activate: false,
            phraseSubmitCustom: "Take a customization",
          },
        },
      },
      materials: [],
    },
    product: {
      id: "gid://shopify/Product/7875607855259",
      title: "The Complete Snowboard",
    },
  },
  {
    id: 66,
    name: "Cliparts cars",
    description: "custom Height",
    icon: "/uploads/clipart110.png",
    popupImg: "",
    data: {
      settings: {
        generals: {
          mobile: {
            showNavigatorMenu: "off",
            showNavigationMenuFirst: "yes",
            mobileSelectionOptionsDisplay: "horizontally",
          },
          output: {
            waterMark: "",
            filesFormat: "png",
            zipOutputFiles: {
              active: false,
              zipOutFolderPrefix: "aso_",
            },
            designComposition: false,
          },
          product: {
            designFromScratch: true,
            redirectAfterAddingToCart: true,
            hideDesignButtonsOnShopPage: true,
            hideAddToCartButtonOnShopPage: false,
            hideAddToCartButtonOnDetailPage: false,
          },
        },
        themeColors: {
          skin: "default",
          colors: {
            textColorButton: "#000000",
            backgroundButton: "#000000",
            textColorButtonHelp: "#000000",
            textColorButtonSave: "#000000",
            textColorHoverButton: "#000000",
            textColorOptionsMenu: "#000000",
            backgroundColorHeader: "#000000",
            textColorContentHeader: "#000000",
            textColorContentSideMenu: "#000000",
            textColorHoverButtonHelp: "#000000",
            textColorHoverButtonSave: "#000000",
            backgroundColorButtonHelp: "#000000",
            textColorButtonRestartAll: "#000000",
            backgroundColorHoverButton: "#000000",
            backgroundColorOptionsMenu: "#000000",
            backgroundColorTextButtonSave: "#000000",
            backgroundColorHoverButtonHelp: "#000000",
            backgroundColorHoverButtonSave: "#000000",
            textColorHoverButtonRestartAll: "#000000",
            backgroundColorButtonRestartAll: "#000000",
            backgroundColorHeaderContentSide: "#000000",
            backgroundColorHoverButtonRestartAll: "#000000",
          },
        },
        customizerSign: {
          text: {
            colors: [],
            enableBold: true,
            enableBorder: true,
            enableItalic: true,
            enableStrike: true,
            enableOpacity: true,
            selectedFonts: [],
            enableCurvedUp: false,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 30,
              minimumFontSize: 12,
            },
            enableOverline: true,
            enableUnderline: true,
            enableCurvedDown: false,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          images: {
            filter: {
              active: true,
              enableBlur: true,
              enableSepia: true,
              enableEmbross: true,
              enableOpacity: true,
              enableSharpen: true,
              enableGreyscale: false,
            },
            enableClipart: {
              active: true,
              selectClipartGroups: [2],
            },
            fileUploadScript: {
              uploadMaxWidth: 100,
              uploadMinWidth: 100,
              customWithGraphical: false,
              allowedUploadsExtentions: ["png"],
            },
            enableUploadImage: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: false,
              enableCopyDesignFromSide: true,
            },
          },
          customizerOptions: {
            measurementUnit: "cm",
            desktopColumnOrder: "right",
            showDayNightButton: "display",
            showHideMeasurements: "both",
            decimalFormatMeasurements: "with-decimal",
          },
        },
        languageImages: {
          images: {
            icon: "",
            resetAllIcon: "",
            cancelAnAction: "",
            changeIconSize: "",
            changeIconText: "",
            changeIconColor: "",
            changeIconImage: "",
            changeIconShape: "",
            changeIconShare: "",
            changeIconBorder: "",
            changeIconImport: "",
            changeIconPreview: "",
            changeIconProduct: "",
            changeIconMaterial: "",
            changeIconSizeMenu: "",
            changeIconSaveProject: "",
            changeIconFixingMethod: "",
            changeIconShareSideBar: "",
          },
          visualizer: {
            textHelp: "Help",
            textSave: "Save",
            textSize: "Size",
            textColor: "Color",
            textImage: "Image",
            textShape: "Shape",
            textShare: "Share",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Plastic Signs",
            textDownload: "Download",
            textMaterial: "Material",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textOptionText: "Text",
            textButtonFinish: "Finish",
            textButtonRefresh: "Restart all",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
          },
          uploadDesign: {
            link: "",
            activate: false,
            phraseSubmitCustom: "Take a customization",
          },
        },
      },
      materials: [],
    },
    product: {},
  },
  {
    id: 68,
    name: "custom Height",
    description: "custom Height",
    icon: "/uploads/fixmethod_hanging_aluminium_popup_image.png",
    popupImg: "",
    data: {
      settings: {
        generals: {
          mobile: {
            showNavigatorMenu: "off",
            showNavigationMenuFirst: "yes",
            mobileSelectionOptionsDisplay: "horizontally",
          },
          output: {
            waterMark: "",
            filesFormat: "png",
            zipOutputFiles: {
              active: false,
              zipOutFolderPrefix: "aso_",
            },
            designComposition: false,
          },
          product: {
            designFromScratch: true,
            redirectAfterAddingToCart: true,
            hideDesignButtonsOnShopPage: true,
            hideAddToCartButtonOnShopPage: false,
            hideAddToCartButtonOnDetailPage: false,
          },
        },
        themeColors: {
          skin: "default",
          colors: {
            textColorButton: "#000000",
            backgroundButton: "#000000",
            textColorButtonHelp: "#000000",
            textColorButtonSave: "#000000",
            textColorHoverButton: "#000000",
            textColorOptionsMenu: "#000000",
            backgroundColorHeader: "#000000",
            textColorContentHeader: "#000000",
            textColorContentSideMenu: "#000000",
            textColorHoverButtonHelp: "#000000",
            textColorHoverButtonSave: "#000000",
            backgroundColorButtonHelp: "#000000",
            textColorButtonRestartAll: "#000000",
            backgroundColorHoverButton: "#000000",
            backgroundColorOptionsMenu: "#000000",
            backgroundColorTextButtonSave: "#000000",
            backgroundColorHoverButtonHelp: "#000000",
            backgroundColorHoverButtonSave: "#000000",
            textColorHoverButtonRestartAll: "#000000",
            backgroundColorButtonRestartAll: "#000000",
            backgroundColorHeaderContentSide: "#000000",
            backgroundColorHoverButtonRestartAll: "#000000",
          },
        },
        customizerSign: {
          text: {
            colors: [],
            enableBold: true,
            enableBorder: true,
            enableItalic: true,
            enableStrike: true,
            enableOpacity: true,
            selectedFonts: [],
            enableCurvedUp: false,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 30,
              minimumFontSize: 12,
            },
            enableOverline: true,
            enableUnderline: true,
            enableCurvedDown: false,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          images: {
            filter: {
              active: true,
              enableBlur: true,
              enableSepia: true,
              enableEmbross: true,
              enableOpacity: true,
              enableSharpen: true,
              enableGreyscale: false,
            },
            enableClipart: {
              active: true,
              selectClipartGroups: [2],
            },
            fileUploadScript: {
              uploadMaxWidth: 100,
              uploadMinWidth: 100,
              customWithGraphical: false,
              allowedUploadsExtentions: ["png"],
            },
            enableUploadImage: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: false,
              enableCopyDesignFromSide: true,
            },
          },
          customizerOptions: {
            measurementUnit: "cm",
            desktopColumnOrder: "right",
            showDayNightButton: "display",
            showHideMeasurements: "both",
            decimalFormatMeasurements: "with-decimal",
          },
        },
        languageImages: {
          images: {
            icon: "",
            resetAllIcon: "",
            cancelAnAction: "",
            changeIconSize: "",
            changeIconText: "",
            changeIconColor: "",
            changeIconImage: "",
            changeIconShape: "",
            changeIconShare: "",
            changeIconBorder: "",
            changeIconImport: "",
            changeIconPreview: "",
            changeIconProduct: "",
            changeIconMaterial: "",
            changeIconSizeMenu: "",
            changeIconSaveProject: "",
            changeIconFixingMethod: "",
            changeIconShareSideBar: "",
          },
          visualizer: {
            textHelp: "Help",
            textSave: "Save",
            textSize: "Size",
            textColor: "Color",
            textImage: "Image",
            textShape: "Shape",
            textShare: "Share",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Plastic Signs",
            textDownload: "Download",
            textMaterial: "Material",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textOptionText: "Text",
            textButtonFinish: "Finish",
            textButtonRefresh: "Restart all",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
          },
          uploadDesign: {
            link: "",
            activate: false,
            phraseSubmitCustom: "Take a customization",
          },
        },
      },
      materials: [],
    },
    product: {},
  },
  {
    id: 64,
    name: "Aso  configuration Test 2",
    description: "Aso  configuration Test 2",
    icon: "/uploads/clipart110.png",
    popupImg: "<p>Aso &nbsp;configuration Test 2</p>",
    data: {
      settings: {
        generals: {
          mobile: {
            showNavigatorMenu: "off",
            showNavigationMenuFirst: "yes",
            mobileSelectionOptionsDisplay: "horizontally",
          },
          output: {
            waterMark: "",
            filesFormat: "png",
            zipOutputFiles: {
              active: false,
              zipOutFolderPrefix: "aso_",
            },
            designComposition: false,
          },
          product: {
            designFromScratch: true,
            redirectAfterAddingToCart: true,
            hideDesignButtonsOnShopPage: true,
            hideAddToCartButtonOnShopPage: false,
            hideAddToCartButtonOnDetailPage: false,
          },
        },
        themeColors: {
          skin: "default",
          colors: {
            textColorButton: "#000000",
            backgroundButton: "#000000",
            textColorButtonHelp: "#000000",
            textColorButtonSave: "#000000",
            textColorHoverButton: "#000000",
            textColorOptionsMenu: "#000000",
            backgroundColorHeader: "#000000",
            textColorContentHeader: "#000000",
            textColorContentSideMenu: "#000000",
            textColorHoverButtonHelp: "#000000",
            textColorHoverButtonSave: "#000000",
            backgroundColorButtonHelp: "#000000",
            textColorButtonRestartAll: "#000000",
            backgroundColorHoverButton: "#000000",
            backgroundColorOptionsMenu: "#000000",
            backgroundColorTextButtonSave: "#000000",
            backgroundColorHoverButtonHelp: "#000000",
            backgroundColorHoverButtonSave: "#000000",
            textColorHoverButtonRestartAll: "#000000",
            backgroundColorButtonRestartAll: "#000000",
            backgroundColorHeaderContentSide: "#000000",
            backgroundColorHoverButtonRestartAll: "#000000",
          },
        },
        customizerSign: {
          text: {
            colors: [],
            enableBold: true,
            enableBorder: true,
            enableItalic: true,
            enableStrike: true,
            enableOpacity: true,
            selectedFonts: [],
            enableCurvedUp: false,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 30,
              minimumFontSize: 12,
            },
            enableOverline: true,
            enableUnderline: true,
            enableCurvedDown: false,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          images: {
            filter: {
              active: true,
              enableBlur: true,
              enableSepia: true,
              enableEmbross: true,
              enableOpacity: true,
              enableSharpen: true,
              enableGreyscale: false,
            },
            enableClipart: {
              active: true,
              selectClipartGroups: [2],
            },
            fileUploadScript: {
              uploadMaxWidth: 100,
              uploadMinWidth: 100,
              customWithGraphical: false,
              allowedUploadsExtentions: ["png"],
            },
            enableUploadImage: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: false,
              enableCopyDesignFromSide: true,
            },
          },
          customizerOptions: {
            measurementUnit: "cm",
            desktopColumnOrder: "right",
            showDayNightButton: "display",
            showHideMeasurements: "both",
            decimalFormatMeasurements: "with-decimal",
          },
        },
        languageImages: {
          images: {
            icon: "",
            resetAllIcon: "",
            cancelAnAction: "",
            changeIconSize: "",
            changeIconText: "",
            changeIconColor: "",
            changeIconImage: "",
            changeIconShape: "",
            changeIconShare: "",
            changeIconBorder: "",
            changeIconImport: "",
            changeIconPreview: "",
            changeIconProduct: "",
            changeIconMaterial: "",
            changeIconSizeMenu: "",
            changeIconSaveProject: "",
            changeIconFixingMethod: "",
            changeIconShareSideBar: "",
          },
          visualizer: {
            textHelp: "Help",
            textSave: "Save",
            textSize: "Size",
            textColor: "Color",
            textImage: "Image",
            textShape: "Shape",
            textShare: "Share",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Plastic Signs",
            textDownload: "Download",
            textMaterial: "Material",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textOptionText: "Text",
            textButtonFinish: "Finish",
            textButtonRefresh: "Restart all",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
          },
          uploadDesign: {
            link: "",
            activate: false,
            phraseSubmitCustom: "Take a customization",
          },
        },
      },
      materials: [
        {
          data: {
            sizes: {
              allSizes: [],
              thickness: {
                active: false,
                values: [],
              },
              customSize: {
                width: {
                  max: 0,
                  min: 0,
                  label: "Custom width",
                },
                active: false,
                height: {
                  max: 0,
                  min: 0,
                  label: "Custom height",
                },
              },
            },
            colors: {
              allColors: [
                {
                  name: "Red ",
                  pattern: {
                    url: "",
                    active: true,
                    codeHex: "#EB4848",
                  },
                  prevImg: "",
                  isDefault: true,
                  textColor: {
                    name: "black",
                    active: true,
                    codeHex: "#000000",
                    sameForBorder: false,
                  },
                  additionalPrice: 0,
                },
                {
                  name: "Green",
                  pattern: {
                    url: "",
                    active: true,
                    codeHex: "#11E229",
                  },
                  prevImg: "",
                  isDefault: false,
                  textColor: {
                    name: "Text white",
                    active: true,
                    codeHex: "#F3E9E9",
                    sameForBorder: false,
                  },
                  additionalPrice: 0,
                },
                {
                  name: "yellow ",
                  pattern: {
                    url: "",
                    active: true,
                    codeHex: "#E0EE14",
                  },
                  prevImg: "",
                  isDefault: false,
                  textColor: {
                    name: "black",
                    active: true,
                    codeHex: "#000000",
                    sameForBorder: false,
                  },
                  additionalPrice: 50,
                },
              ],
              customColors: {
                color: {
                  label: "Custum color",
                  active: true,
                  prevImg:
                    "/uploads/WhatsApp Image 2024-02-08 at 16.23.00.jpeg",
                },
              },
            },
            shapes: [],
            borders: {
              settings: {
                colors: [
                  {
                    name: "red",
                    codeHex: "#9A4444",
                  },
                ],
                enableBorderColor: false,
                enableBorderWidth: false,
              },
              allBorders: [],
            },
            textImages: {
              enableText: true,
              enableImages: true,
            },
            fixingMethods: [],
            additionalOptions: [
              {
                icon: "/uploads/clipart111.png",
                title: "Groupe 1",
                options: [
                  {
                    icon: "/uploads/clipart111.png",
                    image:
                      "/uploads/clipart111.png",
                    title: "option no  red",
                    isDefault: true,
                    description: "option no  red",
                    excludeColors: [0, 2, 1],
                    additionalPrice: 550,
                  },
                ],
                description: "Groupe 1",
              },
            ],
          },
          icon: "/uploads/clipart109.png",
          name: "Material 1",
          type: "simple",
          popImg: "<p>Material 1</p>",
          description: "Material 1",
        },
        {
          data: [
            {
              icon: "/uploads/clipart110.png",
              name: " material advanced (Advance)",
              isDefault: false,
              description: " material advanced (Advance)",
            },
          ],
          icon: "/uploads/clipart110.png",
          name: "material advanced",
          type: "advance",
          popImg: "<p>material advanced</p>",
          description: "material advanced",
        },
        {
          data: {
            sizes: {
              allSizes: [
                {
                  label: "colors",
                  width: 0,
                  height: 0,
                  basePrice: 0,
                  charPrice: 0,
                  isDefault: false,
                  textNumber: 0,
                  maxTextChar: -1,
                  startPriceAtChar: 0,
                },
              ],
              thickness: {
                active: false,
                values: [],
              },
              customSize: {
                width: {
                  max: 0,
                  min: 0,
                  label: "Custom width",
                },
                active: false,
                height: {
                  max: 0,
                  min: 0,
                  label: "Custom height",
                },
              },
            },
            colors: {
              allColors: [
                {
                  name: "colors",
                  pattern: {
                    url: "",
                    active: true,
                    codeHex: "#A86161",
                  },
                  prevImg: "",
                  isDefault: false,
                  textColor: {
                    name: "colors text",
                    active: true,
                    codeHex: "#000000",
                    sameForBorder: false,
                  },
                  additionalPrice: 50,
                },
              ],
              customColors: {},
            },
            shapes: [
              {
                shapeId: 0,
                isDefault: false,
                additionalPrice: 50,
              },
            ],
            borders: {
              settings: {
                colors: [
                  {
                    name: "red",
                    codeHex: "#9A4444",
                  },
                ],
                enableBorderColor: false,
                enableBorderWidth: false,
              },
              allBorders: [
                {
                  isDefault: false,
                  excludeSizes: [],
                  excludeShapes: [],
                  manageBorderId: 0,
                  additionalPrice: 50,
                },
              ],
            },
            textImages: {
              enableText: true,
              enableImages: true,
            },
            fixingMethods: [
              {
                isDefault: false,
                excludeSizes: [],
                excludeShapes: [],
                fixingMethodId: 0,
                additionalPrice: 500,
              },
            ],
            additionalOptions: [
              {
                icon: "/uploads/fixmethod_hanging_aluminium_popup_image.png",
                title: "new group",
                options: [
                  {
                    icon: "/uploads/clipart111.png",
                    image:
                      "/uploads/clipart111.png",
                    title: "new  option ",
                    isDefault: false,
                    description: "new  option ",
                    excludeColors: [0],
                    additionalPrice: 5,
                  },
                ],
                description: "new group",
              },
            ],
          },
          icon: "/uploads/clipart111.png",
          name: "Material simple 2",
          type: "simple",
          popImg: "<p>Material simple</p>",
          description: "Material simple 2",
        },
      ],
    },
    product: {
      id: "gid://shopify/Product/7875607855259",
      title: "The Complete Snowboard",
    },
  },
  {
    id: 57,
    name: "Aso  text Configuration",
    description: "Aso  text Configuration",
    icon: "/uploads/fas5_2.jpg",
    popupImg:
      "/uploads/fas5_1.jpg",
    data: {
      settings: {
        themes: {
          skin: "default",
          colors: {
            textColorButton: "#000000",
            backgroundButton: "#000000",
            textColorButtonHelp: "#ECE2E2",
            textColorButtonSave: "#000000",
            textColorHoverButton: "#000000",
            textColorOptionsMenu: "#000000",
            backgroundColorHeader: "#000000",
            textColorContentHeader: "#000000",
            textColorContentSideMenu: "#000000",
            textColorHoverButtonHelp: "#EFDFDF",
            textColorHoverButtonSave: "#000000",
            backgroundColorButtonHelp: "#F6ECEC",
            textColorButtonRestartAll: "#EEE3E3",
            backgroundColorHoverButton: "#000000",
            backgroundColorOptionsMenu: "#000000",
            backgroundColorTextButtonSave: "#000000",
            backgroundColorHoverButtonHelp: "#F6E1E1",
            backgroundColorHoverButtonSave: "#000000",
            textColorHoverButtonRestartAll: "#E9DADA",
            backgroundColorButtonRestartAll: "#F0EFEF",
            backgroundColorHeaderContentSide: "#000000",
            backgroundColorHoverButtonRestartAll: "#F6EFEF",
          },
        },
        generals: {
          mobile: {
            showNavigatorMenu: "on",
            showNavigationMenuFirst: "yes",
            mobileSelectionOptionsDisplay: "horizontally",
          },
          output: {
            waterMark:
              "/uploads/fas5_2.jpg",
            filesFormat: "png",
            zipOutputFiles: {
              active: false,
              zipOutFolderPrefix: "aso_",
            },
            designComposition: false,
          },
          product: {
            designFromScratch: true,
            redirectAfterAddingToCart: true,
            hideDesignButtonsOnShopPage: true,
            hideAddToCartButtonOnShopPage: false,
            hideAddToCartButtonOnDetailPage: false,
          },
        },
        customizerSign: {
          text: {
            colors: [
              {
                name: "white",
                codeHex: "#FFFFFF",
              },
              {
                name: "red",
                codeHex: "#F72121",
              },
              {
                name: "Back",
                codeHex: "#FFFFFF",
              },
            ],
            enableBold: true,
            enableBorder: true,
            enableItalic: true,
            enableStrike: true,
            enableOpacity: true,
            selectedFonts: [4],
            enableCurvedUp: true,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 30,
              minimumFontSize: 12,
            },
            enableOverline: true,
            enableUnderline: true,
            enableCurvedDown: true,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          images: {
            filter: {
              active: true,
              enableBlur: true,
              enableSepia: true,
              enableEmbross: true,
              enableOpacity: true,
              enableSharpen: true,
              enableGreyscale: true,
            },
            enableClipart: {
              active: true,
              selectClipartGroups: [1, 2],
            },
            fileUploadScript: {
              uploadMaxWidth: 100,
              uploadMinWidth: 100,
              uploadMaxHeight: 1024,
              uploadMinHeight: 1024,
              customWithGraphical: true,
              allowedUploadsExtentions: ["png"],
            },
            enableUploadImage: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: true,
              enableCopyDesignFromSide: true,
            },
          },
          customizerOptions: {
            measurementUnit: "mm",
            desktopColumnOrder: "left",
            showDayNightButton: "display",
            showHideMeasurements: "width",
            decimalFormatMeasurements: "with-decimal",
          },
        },
        languageImages: {
          images: {
            resetAllIcon:
              "/uploads/none-1712079547489.png",
          },
          visualizer: {
            textHelp: "Help",
            textSave: "Save",
            textSize: "Size",
            textColor: "Color",
            textImage: "Image",
            textShape: "Shape",
            textShare: "Share",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Plastic Signs",
            textDownload: "Download",
            textMaterial: "Material",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textOptionText: "Text",
            textButtonFinish: "Finish",
            textButtonRefresh: "Restart all",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
          },
          uploadDesign: {
            link: "url",
            activate: true,
            phraseSubmitCustom: "Take a customization",
          },
        },
      },
      materials: [
        {
          data: {
            sizes: {
              allSizes: [
                {
                  basePrice: 0,
                  charPrice: 0,
                  textNumber: 0,
                  maxTextChar: -1,
                  manageSizeId: 3,
                  startPriceAtChar: 0,
                },
                {
                  basePrice: 0,
                  charPrice: 0,
                  textNumber: 0,
                  maxTextChar: -1,
                  manageSizeId: 3,
                  startPriceAtChar: 20,
                },
              ],
              customSize: {
                width: {
                  max: 0,
                  min: 0,
                  label: "Width",
                },
                active: true,
                height: {
                  max: 501,
                  min: 501,
                  label: "Height",
                },
              },
            },
            colors: [
              {
                manageColorId: 10,
                additionalPrice: 55,
              },
              {
                manageColorId: 11,
                additionalPrice: 25,
              },
              {
                manageColorId: 9,
                additionalPrice: 10,
              },
            ],
            shapes: [
              {
                shapeId: 2,
                additionalPrice: 50,
              },
              {
                shapeId: 7,
                additionalPrice: 50,
              },
              {
                shapeId: 10,
                additionalPrice: 0,
              },
              {
                shapeId: 3,
                additionalPrice: 0,
              },
            ],
            borders: [
              {
                settings: {
                  codeHex: "#C24D4D",
                  enableBorderColor: true,
                  enableBorderWidth: true,
                },
                excludeSizes: [],
                manageBorderId: 0,
                additionalPrice: 55,
              },
            ],
            textImages: {
              enableText: true,
              enableImages: true,
            },
            fixingMethods: [
              {
                fixingMethodId: 2,
                additionalPrice: 55,
              },
              {
                fixingMethodId: 6,
                additionalPrice: 20,
              },
              {
                fixingMethodId: 4,
                additionalPrice: 50,
              },
              {
                fixingMethodId: 9,
                additionalPrice: 5,
              },
            ],
            additionalOptions: [
              {
                icon: "/uploads/thomy.png",
                title: "Texture",
                options: [
                  {
                    icon: "/uploads/woodTexture.png",
                    image:
                      "/uploads/woodTexture.png",
                    title: "Wood Texture",
                    description: "Wood Texture",
                    additionalPrice: 50,
                  },
                  {
                    icon: "/uploads/goldTexture.png",
                    image:
                      "/uploads/goldTexture.png",
                    title: "Gold Texture",
                    description: "Gold Texture",
                    additionalPrice: 58,
                  },
                  {
                    icon: "/uploads/MapTexture.png",
                    image:
                      "/uploads/MapTexture.png",
                    title: "Map  texture",
                    description: "Map  texture",
                    additionalPrice: 10,
                  },
                ],
                description: "Texture",
              },
            ],
          },
          icon: "/uploads/rounded-corners.png",
          name: "Plastic material",
          type: "simple",
          popImg:
            "/uploads/rounded-corners.png",
          description: "Plastic material",
        },
        {
          data: [
            {
              icon: "/uploads/woodTexture.png",
              name: "Wood component",
              options: [
                {
                  icon: "/uploads/woodTexture.png",
                  name: "Wood option1",
                  size: {
                    width: 50,
                    height: 50,
                  },
                  color: {
                    name: "Blue",
                    codeHex: "#194AFA",
                    prevImg:
                      "/uploads/woodTexture.png",
                  },
                  image:
                    "/uploads/woodTexture.png",
                  shapeId: 3,
                  description: "Wood option1",
                  fixingMethods: [3, 2, 1, 0, 4],
                  additionalPrice: 50,
                },
                {
                  icon: "/uploads/goldTexture.png",
                  name: "Gold woood",
                  size: {
                    width: 100,
                    height: 100,
                  },
                  color: {
                    name: "gold color",
                    codeHex: "#F38D1D",
                    prevImg:
                      "/uploads/goldTexture.png",
                  },
                  image:
                    "/uploads/goldTexture.png",
                  shapeId: 0,
                  description: "Gold woood",
                  fixingMethods: [0, 2, 3, 1, 4, 5, 11, 9],
                  additionalPrice: 50,
                },
              ],
              description: "Wood component",
            },
          ],
          icon: "/uploads/screw-1712079632388.png",
          name: "Wood SIgn",
          type: "advance",
          popImg:
            "/uploads/magnetic-trap-1712079614776.png",
          description: "Wood SIgn",
        },
      ],
    },
    product: {
      id: "gid://shopify/Product/7875608248475",
      title: "The Collection Snowboard: Liquid",
    },
  },
  {
    id: 60,
    name: "The Inventory Not Tracked Snowboard config",
    description:
      "The Inventory Not Tracked Snowboard config  The Inventory Not Tracked Snowboard config",
    icon: "/uploads/door_sign-en-adcf12940ac6638c630634435effbefee574530c7b3ff415734bb46888c80b28.webp",
    popupImg:
      "/uploads/door_sign-en-adcf12940ac6638c630634435effbefee574530c7b3ff415734bb46888c80b28.webp",
    data: null,
    product: {
      id: "gid://shopify/Product/7875608215707",
      title: "The Collection Snowboard: Oxygen",
    },
  },
  {
    id: 56,
    name: "Wood Sign1",
    description: "Wood Sign 1",
    icon: "/uploads/screw-tape-1710350698383.png",
    popupImg: "/uploads/magnetic-trap-1710350664693.png",
    data: {
      settings: {
        themes: {
          skin: "couffo",
          colors: {
            textColorButton: "#000000",
            backgroundButton: "#000000",
            textColorButtonHelp: "#000000",
            textColorButtonSave: "#000000",
            textColorHoverButton: "#000000",
            textColorOptionsMenu: "#000000",
            backgroundColorHeader: "#A1FD1A",
            textColorContentHeader: "#D21C1C",
            textColorContentSideMenu: "#8CED0F",
            textColorHoverButtonHelp: "#000000",
            textColorHoverButtonSave: "#000000",
            backgroundColorButtonHelp: "#0E64EC",
            textColorButtonRestartAll: "#000000",
            backgroundColorHoverButton: "#000000",
            backgroundColorOptionsMenu: "#000000",
            backgroundColorTextButtonSave: "#000000",
            backgroundColorHoverButtonHelp: "#000000",
            backgroundColorHoverButtonSave: "#000000",
            textColorHoverButtonRestartAll: "#000000",
            backgroundColorButtonRestartAll: "#E22525",
            backgroundColorHeaderContentSide: "#000000",
            backgroundColorHoverButtonRestartAll: "#000000",
          },
        },
        customizerSign: {
          text: {
            colors: [
              {
                name: "red",
                codeHex: "#BD6767",
              },
            ],
            enableBold: true,
            enableBorder: false,
            enableItalic: true,
            enableStrike: true,
            enableOpacity: false,
            selectedFonts: [4, 3, 2],
            enableCurvedUp: true,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 100,
              minimumFontSize: 10,
            },
            enableOverline: false,
            enableUnderline: false,
            enableCurvedDown: true,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: true,
              enableCopyDesignFromSide: true,
            },
          },
        },
        languageImages: {
          visualizer: {
            textHelp: "Help",
            textSave: "Save",
            textSize: "Size",
            textColor: "Color",
            textImage: "Image",
            textShape: "Shape",
            textShare: "Share",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Plastic Signs",
            textDownload: "Download",
            textMaterial: "Material",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textOptionText: "Text",
            textButtonFinish: "Finish",
            textButtonRefresh: "Restart all",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
          },
        },
      },
      materials: [
        {
          data: {
            sizes: {
              allSizes: [
                {
                  basePrice: 80,
                  charPrice: 850,
                  isDefault: true,
                  textNumber: 5,
                  maxTextChar: 5,
                  manageSizeId: 3,
                  startPriceAtChar: 1,
                },
                {
                  basePrice: 50,
                  charPrice: 5,
                  isDefault: false,
                  textNumber: 5,
                  maxTextChar: 5,
                  manageSizeId: 3,
                  startPriceAtChar: 1,
                },
              ],
              customSize: {
                width: {
                  max: 50,
                  min: 50,
                  label: "Custom  width",
                },
                active: true,
                height: {
                  max: 50,
                  min: 50,
                  label: "custom Height",
                },
              },
            },
            colors: [
              {
                isDefault: false,
                manageColorId: 9,
                additionalPrice: 500,
              },
              {
                isDefault: false,
                manageColorId: 10,
                additionalPrice: 30,
              },
              {
                isDefault: true,
                manageColorId: 13,
                additionalPrice: 252,
              },
            ],
            shapes: [
              {
                shapeId: 8,
                isDefault: false,
                additionalPrice: 50,
              },
              {
                shapeId: 7,
                isDefault: true,
                additionalPrice: 2500,
              },
            ],
            borders: [
              {
                settings: {
                  colors: [
                    {
                      name: "red",
                      codeHex: "#811C1C",
                    },
                    {
                      name: "black",
                      codeHex: "#141212",
                    },
                    {
                      name: "green",
                      codeHex: "#4DF20A",
                    },
                  ],
                  enableBorderColor: true,
                  enableBorderWidth: false,
                },
                isDefault: true,
                excludeSizes: [3],
                manageBorderId: 0,
                additionalPrice: 50,
              },
            ],
            textImages: {
              enableText: false,
              enableImages: true,
            },
            fixingMethods: [
              {
                isDefault: false,
                fixingMethodId: 10,
                additionalPrice: 200,
              },
              {
                isDefault: true,
                fixingMethodId: 5,
                additionalPrice: 2055,
              },
            ],
            additionalOptions: [
              {
                icon: "/uploads/screw-tape-1710334347615.png",
                title: "Deep",
                options: [
                  {
                    icon: "/uploads/magnetic-trap-1710345315421.png",
                    image: "/uploads/magnetic-trap-1710345315421.png",
                    title: "Size 4",
                    isDefault: true,
                    description: "Size 4",
                    additionalPrice: 50,
                  },
                  {
                    icon: "/uploads/screw-tape-1710350677938.png",
                    image: "/uploads/magnetic-trap-1710334268729.png",
                    title: "Size5",
                    isDefault: false,
                    description: "Size5",
                    additionalPrice: 20000,
                  },
                ],
                description: "Deep description",
              },
              {
                icon: "/uploads/screw-tape-1710346079146.png",
                title: "Divider",
                description: "Divider description k",
              },
              {
                icon: "/uploads/screw-tape-1710346079146.png",
                title: "Peinture",
                description: "Peinture",
              },
              {
                icon: "/uploads/adhesive-tape-1710333202815.png",
                title: "Water background",
                description: "Water background",
              },
            ],
          },
          icon: "/uploads/adhesive-tape-1710333631120.png",
          name: "Acrylit 1",
          type: "simple",
          popImg:
            "<h2>QUEL BUDGET PR&Eacute;VOIR POUR VOYAGER AU BR&Eacute;SIL ?</h2>\n<p>Vous &ecirc;tes int&eacute;ress&eacute;s par un voyage au Br&eacute;sil ? Vous devez savoir qu'un certain budget est n&eacute;cessaire, d'abord pour l'achat des billets d'avion. Situ&eacute; loin de la France, ce pays n'est pas accessible pour tout le monde. Comptez environ 600 &euro; pour les vols, par <strong>personne</strong>.</p>\n<ul>\n<li>&nbsp;Une fois sur place, il serait dommage de visiter uniquement une seule ville,</li>\n<li>il faut donc trouver un v&eacute;hicule. La location, pendant une semaine,</li>\n<li>d'une voiture essence vous revient &agrave; minimum<strong> <span style=\"color: #000000;\"><em>150 &euro;.</em></span></strong></li>\n</ul>",
          description: "Acrylit 1",
        },
        {
          data: [
            {
              icon: "/uploads/magnetic-trap-1710346250535.png",
              name: "Component",
              options: [
                {
                  icon: "/uploads/magnetic-trap-1710346233672.png",
                  name: "Options",
                  size: {
                    width: 100,
                    height: 100,
                    basePrice: 0,
                    charPrice: 0,
                    maxTextChar: 2,
                    startPriceAtChar: 1,
                  },
                  color: {
                    name: "red",
                    codeHex: "#DB2727",
                    prevImg: "/uploads/magnetic-trap-1710346233672.png",
                  },
                  image: "/uploads/screw.png",
                  shapeId: 0,
                  isDefault: true,
                  description: "Options",
                  fixingMethods: [2, 1, 4],
                  additionalPrice: 0,
                },
              ],
              isDefault: false,
              description: "Component Component Component",
            },
            {
              icon: "/uploads/brightestwall-1713193291216.jpg",
              name: "wall sign",
              isDefault: true,
              description: "wall sign",
            },
          ],
          icon: "/uploads/magnetic-trap-1710346233672.png",
          name: "Wood materiel",
          type: "advance",
          popImg: "/uploads/magnetic-trap-1710346059768.png",
          description: "Wood materiel",
        },
        {
          data: {
            sizes: {
              allSizes: [
                {
                  label: "Small  size",
                  width: 50,
                  height: 50,
                  basePrice: 50,
                  charPrice: 20,
                  isDefault: true,
                  textNumber: 0,
                  maxTextChar: -1,
                  startPriceAtChar: 0,
                },
                {
                  label: "Medium size",
                  width: 100,
                  height: 100,
                  basePrice: 100,
                  charPrice: 20,
                  isDefault: false,
                  textNumber: 0,
                  maxTextChar: -1,
                  startPriceAtChar: 0,
                },
                {
                  label: "Large size",
                  width: 215,
                  height: 230,
                  basePrice: 200,
                  charPrice: 20,
                  textNumber: 2,
                  maxTextChar: -1,
                  startPriceAtChar: 25,
                },
              ],
              thickness: {
                active: true,
                values: [50, 60, 100, 500],
              },
              customSize: {
                width: {
                  max: 100,
                  min: 50,
                  label: "Custom width",
                },
                active: true,
                height: {
                  max: 100,
                  min: 50,
                  label: "Custom height",
                },
              },
            },
            colors: {
              allColors: [
                {
                  name: "Red",
                  pattern: {
                    url: "/uploads/clipart111.png",
                    active: true,
                    codeHex: "#FD1313",
                  },
                  prevImg:
                    "/uploads/clipart110.png",
                  isDefault: false,
                  textColor: {
                    name: "Black",
                    active: true,
                    codeHex: "#090909",
                    sameForBorder: true,
                  },
                  additionalPrice: 50,
                },
                {
                  name: "Blue",
                  pattern: {
                    url: "",
                    active: true,
                    codeHex: "#000000",
                  },
                  prevImg: "",
                  isDefault: false,
                  textColor: {
                    name: "",
                    active: true,
                    codeHex: "#000000",
                    sameForBorder: false,
                  },
                  additionalPrice: 0,
                },
              ],
              customColors: {
                label: "Custom Colors",
                active: true,
                prevImg:
                  "/uploads/clipart109.png",
              },
            },
            borders: {
              settings: {
                colors: [
                  {
                    name: "white",
                    codeHex: "#FFFFFF",
                  },
                  {
                    name: "Black",
                    codeHex: "#120F0F",
                  },
                ],
                enableBorderColor: true,
                enableBorderWidth: true,
              },
              allBorders: [
                {
                  isDefault: true,
                  excludeSizes: [0, 1],
                  excludeShapes: [1, 0],
                  manageBorderId: 0,
                  additionalPrice: 0,
                },
                {
                  isDefault: false,
                  excludeSizes: [1, 0],
                  excludeShapes: [8],
                  manageBorderId: 0,
                  additionalPrice: 50,
                },
              ],
            },
            fixingMethods: [
              {
                isDefault: true,
                excludeSizes: [],
                excludeShapes: [],
                fixingMethodId: 6,
                additionalPrice: 54,
              },
              {
                isDefault: false,
                excludeSizes: [0, 1],
                excludeShapes: [7, 4],
                fixingMethodId: 2,
                additionalPrice: 50,
              },
              {
                isDefault: false,
                excludeSizes: [],
                excludeShapes: [],
                fixingMethodId: 9,
                additionalPrice: 52,
              },
            ],
          },
          icon: "/uploads/clipart111.png",
          name: "wood simple",
          type: "simple",
          popImg: "<p>wood simple</p>",
          description: "wood simple",
        },
      ],
    },
    product: null,
  },
];
