name: Build and Deploy to Prod Pipeline
on: 
  push:
    branches: [ "ops/ci-pipeline", "stage"  ]
  pull_request:
    branches: [ "main", "stage" ]
jobs:
  build-images:
    name: Build && push frontend image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}"
          echo "::set-output name=version::${VERSION}"

      - name: Setup docker builder
        uses: docker/setup-buildx-action@v3

      - name: Login to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      #- name: Build and push docker image (Stage images)
      #  uses: docker/build-push-action@v6
      #  with:
      #    context: .
      #    push: true
      #    tags: vertimcoders/all-signs-options:latest

      - name: Build Docker image
        id: build
        run: |
          docker build -t vertimcoders/all-signs-options:${{ env.VERSION }} .

      - name: Push Docker image (dev)
        if: github.ref == 'refs/heads/stage'
        run: |
          docker tag vertimcoders/all-signs-options:${{ env.VERSION }} vertimcoders/all-signs-options:${{ env.VERSION }}-dev
          docker push vertimcoders/all-signs-options:${{ env.VERSION }}-dev
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag and push Docker image (main)
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          docker tag vertimcoders/all-signs-options:${{ env.VERSION }} vertimcoders/all-signs-options:latest
          docker tag vertimcoders/all-signs-options:latest vertimcoders/all-signs-options:latest
          docker push vertimcoders/all-signs-options:${{ env.VERSION }}
          docker push vertimcoders/all-signs-options:latest
        env:
          DOCKER_BUILDKIT: 1

  deploy:
    name: Connect to remote and launch apps
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Remote connexion && Start containers
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PWD: ${{ secrets.DOCKERHUB_PASSWORD }}
          PROJECT_NAME: ${{ github.repository }}
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
          SUBDIR: ${{ env.BRANCH_NAME }}
          VERSION: ${{ needs.build-images.outputs.version }}
        with: 
          host: ${{ secrets.VERTIM_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VERTIM_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          envs: DOCKER_USERNAME,DOCKER_PWD,PROJECT_NAME,PROJECT_DIR,SUBDIR,VERSION
          script: |
            cd $PROJECT_DIR
            cd $SUBDIR 
            sed -i 's@ASOIMGVERS@$VERSION@' .env
            echo "$DOCKER_PWD" | docker login --username $DOCKER_USERNAME --password-stdin && 
            docker-compose pull
            docker-compose -p $PROJECT_DIR-$SUBDIR up -d --force-recreate